name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

env:
  VERSION_3_10: "3.10"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.VERSION_3_10 }}

      - name: Cache pipenv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ env.VERSION_3_10 }}-${{ hashFiles('starter/backend/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-${{ env.VERSION_3_10 }}-

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
        working-directory: ./starter/backend

      - name: Install dependencies and lint
        run: |
          pipenv install
          pipenv run lint
        working-directory: ./starter/backend

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.VERSION_3_10 }}

      - name: Cache pipenv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ env.VERSION_3_10 }}-${{ hashFiles('starter/backend/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-${{ env.VERSION_3_10 }}-

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
        working-directory: ./starter/backend

      - name: Install dependencies and test
        run: |
          pipenv install
          pipenv run test
        working-directory: ./starter/backend

  build:
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          docker build --tag mp-backend:latest .
        working-directory: ./starter/backend
